import { defaultConfig } from '../default';
import type { MasjidConfig } from '../types';

/**
 * MAS Brooklyn — GENERATED by scripts/generate-tenant.mjs from the
 * Supabase `mosques` row. `id` MUST equal `mosques.slug` so ConfigProvider
 * can load this tenant's remote branding/logo/Clerk org. Edit branding here if
 * you need overrides beyond what onboarding captured; re-running the generator
 * will overwrite this file.
 */
export const masBrooklynMqb18esxConfig: MasjidConfig = {
  ...defaultConfig,
  id: 'mas-brooklyn-mqb18esx',
  displayName: 'MAS BK',
  tagline: 'MAS Brooklyn',
  colors: {
    ...defaultConfig.colors,
    primary: '14 78 162',
    accent: '79 191 62',
    onboardingBackground: '7 39 81',
    onboardingAccent: '79 191 62',
    onboardingHalo1: '10 56 117',
    onboardingHalo2: '14 78 162',
    onboardingHalo3: '6 31 65',
    onboardingLayer: '4 25 52',
  },
  locale: 'en',
  timezone: 'America/New_York',
  prayerCalculationMethod: 'ISNA',
  clerkOrgId: 'org_3F2ZVtCEkYnjCf8JtytGDN6rBjm',
};
