import { defaultConfig } from '../default';
import type { MasjidConfig } from '../types';

/**
 * Sahla Demo Masjid — GENERATED by scripts/generate-tenant.mjs from the
 * Supabase `mosques` row. `id` MUST equal `mosques.slug` so ConfigProvider
 * can load this tenant's remote branding/logo/Clerk org. Edit branding here if
 * you need overrides beyond what onboarding captured; re-running the generator
 * will overwrite this file.
 */
export const sahlaDemoMasjidMt93mzujConfig: MasjidConfig = {
  ...defaultConfig,
  id: 'sahla-demo-masjid-mt93mzuj',
  displayName: 'Sahla',
  tagline: 'Sahla Demo Masjid',
  colors: {
    ...defaultConfig.colors,
    primary: '10 38 30',
    accent: '184 146 42',
    onboardingBackground: '5 19 15',
    onboardingAccent: '184 146 42',
    onboardingHalo1: '7 27 22',
    onboardingHalo2: '10 38 30',
    onboardingHalo3: '4 15 12',
    onboardingLayer: '3 12 10',
  },
  locale: 'en',
  timezone: 'America/New_York',
  prayerCalculationMethod: 'ISNA',
  clerkOrgId: 'org_3IQEtY0r40wvFYXnOfsPWMJ6hq0',
};
