#!/usr/bin/env node
/**
 * Tenant scaffolder — turns a `mosques.slug` into the four repo edits the app
 * needs to ship a masjid as its own build. Idempotent: re-running for the same
 * slug updates in place instead of duplicating.
 *
 * Generates / updates:
 *   1. src/config/masjids/<slug>.ts        (bundled tenant config; id === slug)
 *   2. src/config/masjids/index.ts          (import + registry entry + export)
 *   3. app.config.ts                         (BUILD_TIME_MASJIDS display-name map)
 *   4. eas.json                              (<slug>-dev/preview/prod profiles)
 *
 * Usage:
 *   node scripts/generate-tenant.mjs <slug>
 *
 * Env (falls back to .env): SUPABASE_URL, SUPABASE_SECRET_KEY
 *
 * Why id === slug: ConfigProvider loads a tenant's remote branding/logo via
 * `.eq('slug', config.id)`, so the bundled id must equal the onboarding slug
 * or no remote override ever lands. See project-multitenant-masjid-config.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// --- tiny .env loader (no dep) -------------------------------------------
function loadEnv() {
  const out = { ...process.env };
  const envPath = join(ROOT, '.env');
  if (existsSync(envPath)) {
    for (const line of readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && out[m[1]] === undefined) out[m[1]] = m[2];
    }
  }
  return out;
}

// --- helpers --------------------------------------------------------------
const camel = (slug) =>
  slug.replace(/[^a-z0-9]+(.)/gi, (_, c) => c.toUpperCase()).replace(/[^a-z0-9]/gi, '');
const titleVar = (slug) => `${camel(slug)}Config`;

/** "#0E4EA2" -> "14 78 162"; null/invalid -> null */
function hexToTriplet(hex) {
  if (!hex) return null;
  const m = String(hex).trim().replace(/^#/, '');
  if (!/^[0-9a-f]{6}$/i.test(m)) return null;
  const n = parseInt(m, 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

/** scale every channel of a triplet by `f` (0..1), clamped */
function shade(triplet, f) {
  return triplet
    .split(' ')
    .map((c) => Math.max(0, Math.min(255, Math.round(Number(c) * f))))
    .join(' ');
}

const CALC_METHOD = { 2: 'ISNA', 3: 'MWL', 4: 'Makkah', 5: 'Egypt', 1: 'Karachi' };

async function fetchMosque(env, slug) {
  const url = env.SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || env.EXPO_PUBLIC_SUPABASE_URL;
  const key = env.SUPABASE_SECRET_KEY || env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('Missing SUPABASE_URL / SUPABASE_SECRET_KEY');
  const res = await fetch(
    `${url}/rest/v1/mosques?slug=eq.${encodeURIComponent(slug)}&select=*`,
    { headers: { apikey: key, Authorization: `Bearer ${key}` } },
  );
  if (!res.ok) throw new Error(`Supabase ${res.status}: ${await res.text()}`);
  const rows = await res.json();
  if (!rows.length) throw new Error(`No mosque with slug "${slug}"`);
  return rows[0];
}

// --- file generators ------------------------------------------------------
function configFile(m, varName) {
  const primary = hexToTriplet(m.brand_color) || '14 78 162';
  const accent = hexToTriplet(m.accent_color) || primary;
  const onbBg = shade(primary, 0.5);
  const onbLayer = shade(primary, 0.32);
  const halo2 = primary;
  const halo1 = shade(primary, 0.72);
  const halo3 = shade(primary, 0.4);
  const display = m.app_name || m.name || m.slug;
  const calc = CALC_METHOD[m.calculation_method] || 'ISNA';

  return `import { defaultConfig } from '../default';
import type { MasjidConfig } from '../types';

/**
 * ${m.name || m.slug} — GENERATED by scripts/generate-tenant.mjs from the
 * Supabase \`mosques\` row. \`id\` MUST equal \`mosques.slug\` so ConfigProvider
 * can load this tenant's remote branding/logo/Clerk org. Edit branding here if
 * you need overrides beyond what onboarding captured; re-running the generator
 * will overwrite this file.
 */
export const ${varName}: MasjidConfig = {
  ...defaultConfig,
  id: '${m.slug}',
  displayName: '${display.replace(/'/g, "\\'")}',
  tagline: '${(m.name || '').replace(/'/g, "\\'")}',
  colors: {
    ...defaultConfig.colors,
    primary: '${primary}',
    accent: '${accent}',
    onboardingBackground: '${onbBg}',
    onboardingAccent: '${accent}',
    onboardingHalo1: '${halo1}',
    onboardingHalo2: '${halo2}',
    onboardingHalo3: '${halo3}',
    onboardingLayer: '${onbLayer}',
  },
  locale: 'en',
  timezone: '${m.timezone || 'America/New_York'}',
  prayerCalculationMethod: '${calc}',${m.clerk_org_id ? `\n  clerkOrgId: '${m.clerk_org_id}',` : ''}
};
`;
}

function updateIndex(slug, varName) {
  const p = join(ROOT, 'src/config/masjids/index.ts');
  let s = readFileSync(p, 'utf8');
  if (s.includes(`from './${slug}'`)) return false; // idempotent
  // import: after the last masjid import line
  s = s.replace(
    /(import \{ \w+Config \} from '\.\/[^']+';\n)(?![\s\S]*import \{ \w+Config \} from '\.\/)/,
    `$1import { ${varName} } from './${slug}';\n`,
  );
  // registry entry: before the closing brace of masjidRegistry
  s = s.replace(
    /(export const masjidRegistry[^{]*\{[\s\S]*?)(\n\};)/,
    `$1\n  [${varName}.id]: ${varName},$2`,
  );
  // export list: add to the trailing `export { ... };`
  s = s.replace(/export \{ ([^}]+) \};/, (_, names) => {
    const list = names.split(',').map((n) => n.trim()).filter(Boolean);
    list.push(varName);
    list.sort();
    return `export { ${list.join(', ')} };`;
  });
  writeFileSync(p, s);
  return true;
}

function updateAppConfig(slug, display) {
  const p = join(ROOT, 'app.config.ts');
  let s = readFileSync(p, 'utf8');
  if (s.includes(`"${slug}":`)) return false;
  s = s.replace(
    /(const BUILD_TIME_MASJIDS[^{]*\{[\s\S]*?)(\n\};)/,
    `$1\n  "${slug}": { displayName: "${display.replace(/"/g, '\\"')}" },$2`,
  );
  writeFileSync(p, s);
  return true;
}

function updateEas(slug) {
  const p = join(ROOT, 'eas.json');
  const j = JSON.parse(readFileSync(p, 'utf8'));
  if (j.build[`${slug}-dev`]) return false;
  j.build[`${slug}-dev`] = { extends: 'base', env: { MASJID_ID: slug }, channel: `${slug}-dev` };
  j.build[`${slug}-preview`] = {
    extends: 'base', distribution: 'internal', env: { MASJID_ID: slug }, channel: `${slug}-preview`,
  };
  j.build[`${slug}-prod`] = {
    extends: 'base', developmentClient: false, distribution: 'store',
    env: { MASJID_ID: slug }, channel: `${slug}-prod`,
  };
  writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
  return true;
}

// --- main -----------------------------------------------------------------
const slug = process.argv[2];
if (!slug) {
  console.error('Usage: node scripts/generate-tenant.mjs <slug>');
  process.exit(1);
}

const env = loadEnv();
const mosque = await fetchMosque(env, slug);
const varName = titleVar(slug);
const display = mosque.app_name || mosque.name || slug;

writeFileSync(join(ROOT, `src/config/masjids/${slug}.ts`), configFile(mosque, varName));
const a = updateIndex(slug, varName);
const b = updateAppConfig(slug, display);
const c = updateEas(slug);

console.log(`✓ tenant "${slug}" (${display})`);
console.log(`  config file  : src/config/masjids/${slug}.ts (written)`);
console.log(`  registry     : ${a ? 'added' : 'already present'}`);
console.log(`  app.config   : ${b ? 'added' : 'already present'}`);
console.log(`  eas profiles : ${c ? 'added' : 'already present'}`);
console.log(`\nNext: set MASJID_ID=${slug} to build this tenant, or run an EAS build with profile ${slug}-prod.`);
